spring.application.name=moneymanager
spring.datasource.url = jdbc:postgresql://dpg-d7rsqgvlk1mc73dcss80-a.frankfurt-postgres.render.com/moneymanager_eph5
spring.datasource.username = moneymanager_eph5_user
spring.datasource.password = ukfRMrAONv87glb9h8JnRH2zD7lIZ94E